require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe GraphemesController do

  # This should return the minimal set of attributes required to create a valid
  # Grapheme. As you add validations to Grapheme, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "language_project" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # GraphemesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all graphemes as @graphemes" do
      grapheme = Grapheme.create! valid_attributes
      get :index, {}, valid_session
      assigns(:graphemes).should eq([grapheme])
    end
  end

  describe "GET show" do
    it "assigns the requested grapheme as @grapheme" do
      grapheme = Grapheme.create! valid_attributes
      get :show, {:id => grapheme.to_param}, valid_session
      assigns(:grapheme).should eq(grapheme)
    end
  end

  describe "GET new" do
    it "assigns a new grapheme as @grapheme" do
      get :new, {}, valid_session
      assigns(:grapheme).should be_a_new(Grapheme)
    end
  end

  describe "GET edit" do
    it "assigns the requested grapheme as @grapheme" do
      grapheme = Grapheme.create! valid_attributes
      get :edit, {:id => grapheme.to_param}, valid_session
      assigns(:grapheme).should eq(grapheme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Grapheme" do
        expect {
          post :create, {:grapheme => valid_attributes}, valid_session
        }.to change(Grapheme, :count).by(1)
      end

      it "assigns a newly created grapheme as @grapheme" do
        post :create, {:grapheme => valid_attributes}, valid_session
        assigns(:grapheme).should be_a(Grapheme)
        assigns(:grapheme).should be_persisted
      end

      it "redirects to the created grapheme" do
        post :create, {:grapheme => valid_attributes}, valid_session
        response.should redirect_to(Grapheme.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved grapheme as @grapheme" do
        # Trigger the behavior that occurs when invalid params are submitted
        Grapheme.any_instance.stub(:save).and_return(false)
        post :create, {:grapheme => { "language_project" => "invalid value" }}, valid_session
        assigns(:grapheme).should be_a_new(Grapheme)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Grapheme.any_instance.stub(:save).and_return(false)
        post :create, {:grapheme => { "language_project" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested grapheme" do
        grapheme = Grapheme.create! valid_attributes
        # Assuming there are no other graphemes in the database, this
        # specifies that the Grapheme created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Grapheme.any_instance.should_receive(:update_attributes).with({ "language_project" => "" })
        put :update, {:id => grapheme.to_param, :grapheme => { "language_project" => "" }}, valid_session
      end

      it "assigns the requested grapheme as @grapheme" do
        grapheme = Grapheme.create! valid_attributes
        put :update, {:id => grapheme.to_param, :grapheme => valid_attributes}, valid_session
        assigns(:grapheme).should eq(grapheme)
      end

      it "redirects to the grapheme" do
        grapheme = Grapheme.create! valid_attributes
        put :update, {:id => grapheme.to_param, :grapheme => valid_attributes}, valid_session
        response.should redirect_to(grapheme)
      end
    end

    describe "with invalid params" do
      it "assigns the grapheme as @grapheme" do
        grapheme = Grapheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Grapheme.any_instance.stub(:save).and_return(false)
        put :update, {:id => grapheme.to_param, :grapheme => { "language_project" => "invalid value" }}, valid_session
        assigns(:grapheme).should eq(grapheme)
      end

      it "re-renders the 'edit' template" do
        grapheme = Grapheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Grapheme.any_instance.stub(:save).and_return(false)
        put :update, {:id => grapheme.to_param, :grapheme => { "language_project" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested grapheme" do
      grapheme = Grapheme.create! valid_attributes
      expect {
        delete :destroy, {:id => grapheme.to_param}, valid_session
      }.to change(Grapheme, :count).by(-1)
    end

    it "redirects to the graphemes list" do
      grapheme = Grapheme.create! valid_attributes
      delete :destroy, {:id => grapheme.to_param}, valid_session
      response.should redirect_to(graphemes_url)
    end
  end

end
