require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LanguageProjectsController do

  # This should return the minimal set of attributes required to create a valid
  # LanguageProject. As you add validations to LanguageProject, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "slug" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LanguageProjectsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all language_projects as @language_projects" do
      language_project = LanguageProject.create! valid_attributes
      get :index, {}, valid_session
      assigns(:language_projects).should eq([language_project])
    end
  end

  describe "GET show" do
    it "assigns the requested language_project as @language_project" do
      language_project = LanguageProject.create! valid_attributes
      get :show, {:id => language_project.to_param}, valid_session
      assigns(:language_project).should eq(language_project)
    end
  end

  describe "GET new" do
    it "assigns a new language_project as @language_project" do
      get :new, {}, valid_session
      assigns(:language_project).should be_a_new(LanguageProject)
    end
  end

  describe "GET edit" do
    it "assigns the requested language_project as @language_project" do
      language_project = LanguageProject.create! valid_attributes
      get :edit, {:id => language_project.to_param}, valid_session
      assigns(:language_project).should eq(language_project)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LanguageProject" do
        expect {
          post :create, {:language_project => valid_attributes}, valid_session
        }.to change(LanguageProject, :count).by(1)
      end

      it "assigns a newly created language_project as @language_project" do
        post :create, {:language_project => valid_attributes}, valid_session
        assigns(:language_project).should be_a(LanguageProject)
        assigns(:language_project).should be_persisted
      end

      it "redirects to the created language_project" do
        post :create, {:language_project => valid_attributes}, valid_session
        response.should redirect_to(LanguageProject.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved language_project as @language_project" do
        # Trigger the behavior that occurs when invalid params are submitted
        LanguageProject.any_instance.stub(:save).and_return(false)
        post :create, {:language_project => { "slug" => "invalid value" }}, valid_session
        assigns(:language_project).should be_a_new(LanguageProject)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LanguageProject.any_instance.stub(:save).and_return(false)
        post :create, {:language_project => { "slug" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested language_project" do
        language_project = LanguageProject.create! valid_attributes
        # Assuming there are no other language_projects in the database, this
        # specifies that the LanguageProject created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LanguageProject.any_instance.should_receive(:update_attributes).with({ "slug" => "MyString" })
        put :update, {:id => language_project.to_param, :language_project => { "slug" => "MyString" }}, valid_session
      end

      it "assigns the requested language_project as @language_project" do
        language_project = LanguageProject.create! valid_attributes
        put :update, {:id => language_project.to_param, :language_project => valid_attributes}, valid_session
        assigns(:language_project).should eq(language_project)
      end

      it "redirects to the language_project" do
        language_project = LanguageProject.create! valid_attributes
        put :update, {:id => language_project.to_param, :language_project => valid_attributes}, valid_session
        response.should redirect_to(language_project)
      end
    end

    describe "with invalid params" do
      it "assigns the language_project as @language_project" do
        language_project = LanguageProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LanguageProject.any_instance.stub(:save).and_return(false)
        put :update, {:id => language_project.to_param, :language_project => { "slug" => "invalid value" }}, valid_session
        assigns(:language_project).should eq(language_project)
      end

      it "re-renders the 'edit' template" do
        language_project = LanguageProject.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LanguageProject.any_instance.stub(:save).and_return(false)
        put :update, {:id => language_project.to_param, :language_project => { "slug" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested language_project" do
      language_project = LanguageProject.create! valid_attributes
      expect {
        delete :destroy, {:id => language_project.to_param}, valid_session
      }.to change(LanguageProject, :count).by(-1)
    end

    it "redirects to the language_projects list" do
      language_project = LanguageProject.create! valid_attributes
      delete :destroy, {:id => language_project.to_param}, valid_session
      response.should redirect_to(language_projects_url)
    end
  end

end
