require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SentenceWordsController do

  # This should return the minimal set of attributes required to create a valid
  # SentenceWord. As you add validations to SentenceWord, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "position" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SentenceWordsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sentence_words as @sentence_words" do
      sentence_word = SentenceWord.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sentence_words).should eq([sentence_word])
    end
  end

  describe "GET show" do
    it "assigns the requested sentence_word as @sentence_word" do
      sentence_word = SentenceWord.create! valid_attributes
      get :show, {:id => sentence_word.to_param}, valid_session
      assigns(:sentence_word).should eq(sentence_word)
    end
  end

  describe "GET new" do
    it "assigns a new sentence_word as @sentence_word" do
      get :new, {}, valid_session
      assigns(:sentence_word).should be_a_new(SentenceWord)
    end
  end

  describe "GET edit" do
    it "assigns the requested sentence_word as @sentence_word" do
      sentence_word = SentenceWord.create! valid_attributes
      get :edit, {:id => sentence_word.to_param}, valid_session
      assigns(:sentence_word).should eq(sentence_word)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SentenceWord" do
        expect {
          post :create, {:sentence_word => valid_attributes}, valid_session
        }.to change(SentenceWord, :count).by(1)
      end

      it "assigns a newly created sentence_word as @sentence_word" do
        post :create, {:sentence_word => valid_attributes}, valid_session
        assigns(:sentence_word).should be_a(SentenceWord)
        assigns(:sentence_word).should be_persisted
      end

      it "redirects to the created sentence_word" do
        post :create, {:sentence_word => valid_attributes}, valid_session
        response.should redirect_to(SentenceWord.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sentence_word as @sentence_word" do
        # Trigger the behavior that occurs when invalid params are submitted
        SentenceWord.any_instance.stub(:save).and_return(false)
        post :create, {:sentence_word => { "position" => "invalid value" }}, valid_session
        assigns(:sentence_word).should be_a_new(SentenceWord)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SentenceWord.any_instance.stub(:save).and_return(false)
        post :create, {:sentence_word => { "position" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sentence_word" do
        sentence_word = SentenceWord.create! valid_attributes
        # Assuming there are no other sentence_words in the database, this
        # specifies that the SentenceWord created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SentenceWord.any_instance.should_receive(:update_attributes).with({ "position" => "1" })
        put :update, {:id => sentence_word.to_param, :sentence_word => { "position" => "1" }}, valid_session
      end

      it "assigns the requested sentence_word as @sentence_word" do
        sentence_word = SentenceWord.create! valid_attributes
        put :update, {:id => sentence_word.to_param, :sentence_word => valid_attributes}, valid_session
        assigns(:sentence_word).should eq(sentence_word)
      end

      it "redirects to the sentence_word" do
        sentence_word = SentenceWord.create! valid_attributes
        put :update, {:id => sentence_word.to_param, :sentence_word => valid_attributes}, valid_session
        response.should redirect_to(sentence_word)
      end
    end

    describe "with invalid params" do
      it "assigns the sentence_word as @sentence_word" do
        sentence_word = SentenceWord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SentenceWord.any_instance.stub(:save).and_return(false)
        put :update, {:id => sentence_word.to_param, :sentence_word => { "position" => "invalid value" }}, valid_session
        assigns(:sentence_word).should eq(sentence_word)
      end

      it "re-renders the 'edit' template" do
        sentence_word = SentenceWord.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SentenceWord.any_instance.stub(:save).and_return(false)
        put :update, {:id => sentence_word.to_param, :sentence_word => { "position" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sentence_word" do
      sentence_word = SentenceWord.create! valid_attributes
      expect {
        delete :destroy, {:id => sentence_word.to_param}, valid_session
      }.to change(SentenceWord, :count).by(-1)
    end

    it "redirects to the sentence_words list" do
      sentence_word = SentenceWord.create! valid_attributes
      delete :destroy, {:id => sentence_word.to_param}, valid_session
      response.should redirect_to(sentence_words_url)
    end
  end

end
