require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SpellingPatternsController do

  # This should return the minimal set of attributes required to create a valid
  # SpellingPattern. As you add validations to SpellingPattern, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "language_project" => "" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SpellingPatternsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all spelling_patterns as @spelling_patterns" do
      spelling_pattern = SpellingPattern.create! valid_attributes
      get :index, {}, valid_session
      assigns(:spelling_patterns).should eq([spelling_pattern])
    end
  end

  describe "GET show" do
    it "assigns the requested spelling_pattern as @spelling_pattern" do
      spelling_pattern = SpellingPattern.create! valid_attributes
      get :show, {:id => spelling_pattern.to_param}, valid_session
      assigns(:spelling_pattern).should eq(spelling_pattern)
    end
  end

  describe "GET new" do
    it "assigns a new spelling_pattern as @spelling_pattern" do
      get :new, {}, valid_session
      assigns(:spelling_pattern).should be_a_new(SpellingPattern)
    end
  end

  describe "GET edit" do
    it "assigns the requested spelling_pattern as @spelling_pattern" do
      spelling_pattern = SpellingPattern.create! valid_attributes
      get :edit, {:id => spelling_pattern.to_param}, valid_session
      assigns(:spelling_pattern).should eq(spelling_pattern)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SpellingPattern" do
        expect {
          post :create, {:spelling_pattern => valid_attributes}, valid_session
        }.to change(SpellingPattern, :count).by(1)
      end

      it "assigns a newly created spelling_pattern as @spelling_pattern" do
        post :create, {:spelling_pattern => valid_attributes}, valid_session
        assigns(:spelling_pattern).should be_a(SpellingPattern)
        assigns(:spelling_pattern).should be_persisted
      end

      it "redirects to the created spelling_pattern" do
        post :create, {:spelling_pattern => valid_attributes}, valid_session
        response.should redirect_to(SpellingPattern.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved spelling_pattern as @spelling_pattern" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpellingPattern.any_instance.stub(:save).and_return(false)
        post :create, {:spelling_pattern => { "language_project" => "invalid value" }}, valid_session
        assigns(:spelling_pattern).should be_a_new(SpellingPattern)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SpellingPattern.any_instance.stub(:save).and_return(false)
        post :create, {:spelling_pattern => { "language_project" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested spelling_pattern" do
        spelling_pattern = SpellingPattern.create! valid_attributes
        # Assuming there are no other spelling_patterns in the database, this
        # specifies that the SpellingPattern created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SpellingPattern.any_instance.should_receive(:update_attributes).with({ "language_project" => "" })
        put :update, {:id => spelling_pattern.to_param, :spelling_pattern => { "language_project" => "" }}, valid_session
      end

      it "assigns the requested spelling_pattern as @spelling_pattern" do
        spelling_pattern = SpellingPattern.create! valid_attributes
        put :update, {:id => spelling_pattern.to_param, :spelling_pattern => valid_attributes}, valid_session
        assigns(:spelling_pattern).should eq(spelling_pattern)
      end

      it "redirects to the spelling_pattern" do
        spelling_pattern = SpellingPattern.create! valid_attributes
        put :update, {:id => spelling_pattern.to_param, :spelling_pattern => valid_attributes}, valid_session
        response.should redirect_to(spelling_pattern)
      end
    end

    describe "with invalid params" do
      it "assigns the spelling_pattern as @spelling_pattern" do
        spelling_pattern = SpellingPattern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpellingPattern.any_instance.stub(:save).and_return(false)
        put :update, {:id => spelling_pattern.to_param, :spelling_pattern => { "language_project" => "invalid value" }}, valid_session
        assigns(:spelling_pattern).should eq(spelling_pattern)
      end

      it "re-renders the 'edit' template" do
        spelling_pattern = SpellingPattern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SpellingPattern.any_instance.stub(:save).and_return(false)
        put :update, {:id => spelling_pattern.to_param, :spelling_pattern => { "language_project" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested spelling_pattern" do
      spelling_pattern = SpellingPattern.create! valid_attributes
      expect {
        delete :destroy, {:id => spelling_pattern.to_param}, valid_session
      }.to change(SpellingPattern, :count).by(-1)
    end

    it "redirects to the spelling_patterns list" do
      spelling_pattern = SpellingPattern.create! valid_attributes
      delete :destroy, {:id => spelling_pattern.to_param}, valid_session
      response.should redirect_to(spelling_patterns_url)
    end
  end

end
