require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WordSpellingPatternsController do

  # This should return the minimal set of attributes required to create a valid
  # WordSpellingPattern. As you add validations to WordSpellingPattern, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "position" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WordSpellingPatternsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all word_spelling_patterns as @word_spelling_patterns" do
      word_spelling_pattern = WordSpellingPattern.create! valid_attributes
      get :index, {}, valid_session
      assigns(:word_spelling_patterns).should eq([word_spelling_pattern])
    end
  end

  describe "GET show" do
    it "assigns the requested word_spelling_pattern as @word_spelling_pattern" do
      word_spelling_pattern = WordSpellingPattern.create! valid_attributes
      get :show, {:id => word_spelling_pattern.to_param}, valid_session
      assigns(:word_spelling_pattern).should eq(word_spelling_pattern)
    end
  end

  describe "GET new" do
    it "assigns a new word_spelling_pattern as @word_spelling_pattern" do
      get :new, {}, valid_session
      assigns(:word_spelling_pattern).should be_a_new(WordSpellingPattern)
    end
  end

  describe "GET edit" do
    it "assigns the requested word_spelling_pattern as @word_spelling_pattern" do
      word_spelling_pattern = WordSpellingPattern.create! valid_attributes
      get :edit, {:id => word_spelling_pattern.to_param}, valid_session
      assigns(:word_spelling_pattern).should eq(word_spelling_pattern)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WordSpellingPattern" do
        expect {
          post :create, {:word_spelling_pattern => valid_attributes}, valid_session
        }.to change(WordSpellingPattern, :count).by(1)
      end

      it "assigns a newly created word_spelling_pattern as @word_spelling_pattern" do
        post :create, {:word_spelling_pattern => valid_attributes}, valid_session
        assigns(:word_spelling_pattern).should be_a(WordSpellingPattern)
        assigns(:word_spelling_pattern).should be_persisted
      end

      it "redirects to the created word_spelling_pattern" do
        post :create, {:word_spelling_pattern => valid_attributes}, valid_session
        response.should redirect_to(WordSpellingPattern.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved word_spelling_pattern as @word_spelling_pattern" do
        # Trigger the behavior that occurs when invalid params are submitted
        WordSpellingPattern.any_instance.stub(:save).and_return(false)
        post :create, {:word_spelling_pattern => { "position" => "invalid value" }}, valid_session
        assigns(:word_spelling_pattern).should be_a_new(WordSpellingPattern)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WordSpellingPattern.any_instance.stub(:save).and_return(false)
        post :create, {:word_spelling_pattern => { "position" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested word_spelling_pattern" do
        word_spelling_pattern = WordSpellingPattern.create! valid_attributes
        # Assuming there are no other word_spelling_patterns in the database, this
        # specifies that the WordSpellingPattern created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WordSpellingPattern.any_instance.should_receive(:update_attributes).with({ "position" => "1" })
        put :update, {:id => word_spelling_pattern.to_param, :word_spelling_pattern => { "position" => "1" }}, valid_session
      end

      it "assigns the requested word_spelling_pattern as @word_spelling_pattern" do
        word_spelling_pattern = WordSpellingPattern.create! valid_attributes
        put :update, {:id => word_spelling_pattern.to_param, :word_spelling_pattern => valid_attributes}, valid_session
        assigns(:word_spelling_pattern).should eq(word_spelling_pattern)
      end

      it "redirects to the word_spelling_pattern" do
        word_spelling_pattern = WordSpellingPattern.create! valid_attributes
        put :update, {:id => word_spelling_pattern.to_param, :word_spelling_pattern => valid_attributes}, valid_session
        response.should redirect_to(word_spelling_pattern)
      end
    end

    describe "with invalid params" do
      it "assigns the word_spelling_pattern as @word_spelling_pattern" do
        word_spelling_pattern = WordSpellingPattern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WordSpellingPattern.any_instance.stub(:save).and_return(false)
        put :update, {:id => word_spelling_pattern.to_param, :word_spelling_pattern => { "position" => "invalid value" }}, valid_session
        assigns(:word_spelling_pattern).should eq(word_spelling_pattern)
      end

      it "re-renders the 'edit' template" do
        word_spelling_pattern = WordSpellingPattern.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WordSpellingPattern.any_instance.stub(:save).and_return(false)
        put :update, {:id => word_spelling_pattern.to_param, :word_spelling_pattern => { "position" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested word_spelling_pattern" do
      word_spelling_pattern = WordSpellingPattern.create! valid_attributes
      expect {
        delete :destroy, {:id => word_spelling_pattern.to_param}, valid_session
      }.to change(WordSpellingPattern, :count).by(-1)
    end

    it "redirects to the word_spelling_patterns list" do
      word_spelling_pattern = WordSpellingPattern.create! valid_attributes
      delete :destroy, {:id => word_spelling_pattern.to_param}, valid_session
      response.should redirect_to(word_spelling_patterns_url)
    end
  end

end
